//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GlobalResQueryTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GlobalResQueryTable")]
  public partial class GlobalResQueryTable : global::ProtoBuf.IExtensible,global::ProtoBuf.IParseable
  {
    public GlobalResQueryTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _assetPackageIndex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"assetPackageIndex", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int assetPackageIndex
    {
      get { return _assetPackageIndex; }
      set { _assetPackageIndex = value; }
    }
    private string _AssetBundlePath;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"AssetBundlePath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AssetBundlePath
    {
      get { return _AssetBundlePath; }
      set { _AssetBundlePath = value; }
    }
    private string _assetName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"assetName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string assetName
    {
      get { return _assetName; }
      set { _assetName = value; }
    }
    private string _fileMd5;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"fileMd5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fileMd5
    {
      get { return _fileMd5; }
      set { _fileMd5 = value; }
    }
    public void Parse(ProtoBuf.ProtoReader source){
        int fieldNumber = 0;
        while ((fieldNumber = source.ReadFieldHeader()) > 0)
        {
            switch (fieldNumber)
            {
                default:
                    source.SkipField();
                    break;
            
    
            case 1:   //ID LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    ID = source.ReadInt32();
                    break;
                    
            case 2:   //assetPackageIndex LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    assetPackageIndex = source.ReadInt32();
                    break;
                    
            case 3:   //AssetBundlePath LABEL_REQUIRED TYPE_STRING  TwosComplement
                    AssetBundlePath = source.ReadString();
                    break;
                    
            case 4:   //assetName LABEL_REQUIRED TYPE_STRING  TwosComplement
                    assetName = source.ReadString();
                    break;
                    
            case 5:   //fileMd5 LABEL_REQUIRED TYPE_STRING  TwosComplement
                    fileMd5 = source.ReadString();
                    break;
                    
            }
        }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}