//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ModuleTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ModuleTable")]
  public partial class ModuleTable : global::ProtoBuf.IExtensible,global::ProtoBuf.IParseable
  {
    public ModuleTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _ModuleName = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"ModuleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> ModuleName
    {
      get { return _ModuleName; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _RequiredBundles = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"RequiredBundles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> RequiredBundles
    {
      get { return _RequiredBundles; }
    }
  
    public void Parse(ProtoBuf.ProtoReader source){
        int fieldNumber = 0;
        while ((fieldNumber = source.ReadFieldHeader()) > 0)
        {
            switch (fieldNumber)
            {
                default:
                    source.SkipField();
                    break;
            
    
            case 1:   //ID LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    ID = source.ReadInt32();
                    break;
                    
            case 2:   //ModuleName LABEL_REPEATED TYPE_STRING  TwosComplement
                    int ModuleNamefield = source.FieldNumber;
                    do{
                        ModuleName.Add(source.ReadString());
                    } while(source.TryReadFieldHeader(ModuleNamefield));
                    break;
                    
            case 3:   //RequiredBundles LABEL_REPEATED TYPE_STRING  TwosComplement
                    int RequiredBundlesfield = source.FieldNumber;
                    do{
                        RequiredBundles.Add(source.ReadString());
                    } while(source.TryReadFieldHeader(RequiredBundlesfield));
                    break;
                    
            }
        }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}