//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ResourceInfoTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceInfoTable")]
  public partial class ResourceInfoTable : global::ProtoBuf.IExtensible,global::ProtoBuf.IParseable
  {
    public ResourceInfoTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private ProtoTable.ResourceInfoTable.eLoadType _LoadType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"LoadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.ResourceInfoTable.eLoadType LoadType
    {
      get { return _LoadType; }
      set { _LoadType = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _Path = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> Path
    {
      get { return _Path; }
    }
  
    private string _PathHashKey;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"PathHashKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PathHashKey
    {
      get { return _PathHashKey; }
      set { _PathHashKey = value; }
    }
    private int _TypeId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"TypeId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int TypeId
    {
      get { return _TypeId; }
      set { _TypeId = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eLoadType")]
    public enum eLoadType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoadFromResources", Value=0)]
      LoadFromResources = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoadFromBundle", Value=1)]
      LoadFromBundle = 1
    }
  
    public void Parse(ProtoBuf.ProtoReader source){
        int fieldNumber = 0;
        while ((fieldNumber = source.ReadFieldHeader()) > 0)
        {
            switch (fieldNumber)
            {
                default:
                    source.SkipField();
                    break;
            
    
            case 1:   //ID LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    ID = source.ReadInt32();
                    break;
                    
            case 2:   //LoadType LABEL_REQUIRED TYPE_ENUM .ProtoTable.ResourceInfoTable.eLoadType TwosComplement
                    LoadType = (ProtoTable.ResourceInfoTable.eLoadType)source.ReadInt32();
                    break;
                    
            case 3:   //Path LABEL_REPEATED TYPE_STRING  TwosComplement
                    int Pathfield = source.FieldNumber;
                    do{
                        Path.Add(source.ReadString());
                    } while(source.TryReadFieldHeader(Pathfield));
                    break;
                    
            case 4:   //PathHashKey LABEL_REQUIRED TYPE_STRING  TwosComplement
                    PathHashKey = source.ReadString();
                    break;
                    
            case 5:   //TypeId LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    TypeId = source.ReadInt32();
                    break;
                    
            }
        }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}