//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: VersionConfigTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VersionConfigTable")]
  public partial class VersionConfigTable : global::ProtoBuf.IExtensible,global::ProtoBuf.IParseable
  {
    public VersionConfigTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _Version;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Version", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Version
    {
      get { return _Version; }
      set { _Version = value; }
    }
    private int _NeedUpdateAll;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"NeedUpdateAll", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int NeedUpdateAll
    {
      get { return _NeedUpdateAll; }
      set { _NeedUpdateAll = value; }
    }
    private string _Desc;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Desc
    {
      get { return _Desc; }
      set { _Desc = value; }
    }
    private string _IosUrl;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"IosUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string IosUrl
    {
      get { return _IosUrl; }
      set { _IosUrl = value; }
    }
    private string _AndroidUrl;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"AndroidUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AndroidUrl
    {
      get { return _AndroidUrl; }
      set { _AndroidUrl = value; }
    }
    public void Parse(ProtoBuf.ProtoReader source){
        int fieldNumber = 0;
        while ((fieldNumber = source.ReadFieldHeader()) > 0)
        {
            switch (fieldNumber)
            {
                default:
                    source.SkipField();
                    break;
            
    
            case 1:   //ID LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    ID = source.ReadInt32();
                    break;
                    
            case 2:   //Version LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    Version = source.ReadInt32();
                    break;
                    
            case 3:   //NeedUpdateAll LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    NeedUpdateAll = source.ReadInt32();
                    break;
                    
            case 4:   //Desc LABEL_REQUIRED TYPE_STRING  TwosComplement
                    Desc = source.ReadString();
                    break;
                    
            case 5:   //IosUrl LABEL_REQUIRED TYPE_STRING  TwosComplement
                    IosUrl = source.ReadString();
                    break;
                    
            case 6:   //AndroidUrl LABEL_REQUIRED TYPE_STRING  TwosComplement
                    AndroidUrl = source.ReadString();
                    break;
                    
            }
        }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}